### ISSUE TITLE
GraphQL implementation (?)

### ISSUE THREAD

**Issue by lucascassiano** [davidcostadev/fastexpress#19]
with the advance of GraphQL, should we add few GraphQL features? I have a few examples I used before that I can implement on my fork and submit a PR here 

is it in the RoadMap desired for this API?

**Comment by davidcostadev** [comment]
That is an excellent ideal, For now, I just put with Sequelize that mean that just it will be used with Mysql, Postgresql, I wanted to add integration with MongoDB too, I maybe GraphQL too. I will glad any help to do this.

**Comment by davidcostadev** [comment]
The Fastexpress need to be a collection of function to speed the development with express. And not just for REST only.

**Comment by davidcostadev** [comment]
I will close this issue because, what I that to do here is a RESTFUL API that is different method of API, and use GraphQL is a divergent ideal. Thank you to ask.
