### ISSUE TITLE
Give proper folders or files to utils/helpers.

### ISSUE THREAD

**Issue by diasbruno** [davidcostadev/fastexpress#20]
It's always nice to have a clear separation of the tools needed on a project.

Instead of dumping everything on the utils/helpers files, try to give those functions a real home.

Ex: If you have a collection of functions that deals with `text`, create a `lib/text.js`, for `sets`, create a file `lib/sets.js` and so on.

**Comment by davidcostadev** [comment]
First thanks for this issue, I think that is a great idea it yours.

**Comment by davidcostadev** [comment]
I implemented this advice on #44 where i'm working on the new version of fastexpress.
