### ISSUE TITLE
Add a simple CLI to the project

### ISSUE THREAD

**Issue by gustavoFreireS** [davidcostadev/fastexpress#35]
I nice thing to have in a framework like this is a basic CLI something like rails does with his `rails new "project name"` and  `rails generate scaffold someResource: string` wold be enough I'm thinking about something like: `fast create "project name"` and `fast generate resourceName: string` for starters also for the new project template we could just render a root route with a simple message like "it's working" or something

**Comment by davidcostadev** [comment]
#91

**Comment by davidcostadev** [comment]
I think that the basic propose as completed, Thanks @gustavoFreireS
