### ISSUE TITLE
Basic example migrations error

### ISSUE THREAD

**Issue by gustavoFreireS** [davidcostadev/fastexpress#36]
on the basic example (latest version) the migrations folder should be on **root** folder outside **src** folder (yarn gave me the following error: `ENOENT: no such file or directory, scandir '{my-path}/basic/migrations'`)

**Comment by davidcostadev** [comment]
Please, can you give more information?

- What the step that you took?
- What version you are using?
- What is command that you try to use?

**Comment by davidcostadev** [comment]
@gustavoFreireS please check this pull request #39 and tell me if fix that problem

**Comment by gustavoFreireS** [comment]
now is fixed on https://github.com/davidcostadev/fastexpress/pull/39

**Comment by davidcostadev** [comment]
Thanks @gustavoFreireS
