### ISSUE TITLE
Basic example start script error

### ISSUE THREAD

**Issue by gustavoFreireS** [davidcostadev/fastexpress#37]
The first time I tried to start the project (latest version) with the `yarn run start` command it sent this error:
 ```
ReferenceError: custom is not defined
    at exports.serviceDefaultProps (/Users/gustavofreiresantos/projetos/not-a-real-bank-api/node_modules/fastexpress/cjs/service/createService.js:24:3)
```
 just deleting the "custom" field at line 24  from createService.js solved the issue for me

**Comment by davidcostadev** [comment]
Thank @gustavoFreireS for Help, I that launch fix version, can you install and test again?

**Comment by davidcostadev** [comment]
Hey, @gustavoFreireS I will close this issue, if this problem happens again, please open another issue.
